server:
  port: 8081

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Manevy22/Config-Server-Practice.git
          searchPaths: config-data
          username: Manevy22
          password: JoseFinaPatitas2024
