server:
    port: 8081

spring:
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/Manevy22/Config-Server-Practice-Manevy.git
                    search-paths: config-data
                    username: ${GIT_USERNAME}
                    password: ${GIT_PASSWORD}

